diff --git a/subprojects/groovy-servlet/src/main/java/groovy/servlet/TemplateServlet.java b/subprojects/groovy-servlet/src/main/java/groovy/servlet/TemplateServlet.java
index 94e835e..552c7b9 100644
--- a/subprojects/groovy-servlet/src/main/java/groovy/servlet/TemplateServlet.java
+++ b/subprojects/groovy-servlet/src/main/java/groovy/servlet/TemplateServlet.java
@@ -486,7 +486,7 @@
         makeMillis = System.currentTimeMillis() - makeMillis;
 
         if (generateBy) {
-            StringBuffer sb = new StringBuffer(100);
+            StringBuilder sb = new StringBuilder(100);
             sb.append("\n<!-- Generated by Groovy TemplateServlet [create/get=");
             sb.append(Long.toString(getMillis));
             sb.append(" ms, make=");
