diff --git a/core/src/main/java/com/google/errorprone/bugpatterns/BugChecker.java b/core/src/main/java/com/google/errorprone/bugpatterns/BugChecker.java
index eddc241..41b5438 100644
--- a/core/src/main/java/com/google/errorprone/bugpatterns/BugChecker.java
+++ b/core/src/main/java/com/google/errorprone/bugpatterns/BugChecker.java
@@ -177,7 +177,7 @@
 
   private static String createLinkUrl(BugPattern pattern) {
     switch (pattern.linkType()) {
-      case WIKI:
+      case AUTOGENERATED:
         return String.format("http://errorprone.info/bugpattern/%s", pattern.name());
       case CUSTOM:
         // annotation.link() must be provided.
