diff --git a/src-gen/com/facebook/buck/distributed/thrift/FrontendRequest.java b/src-gen/com/facebook/buck/distributed/thrift/FrontendRequest.java
index 259a8b0..1da700c 100644
--- a/src-gen/com/facebook/buck/distributed/thrift/FrontendRequest.java
+++ b/src-gen/com/facebook/buck/distributed/thrift/FrontendRequest.java
@@ -34,14 +34,14 @@
 import org.slf4j.LoggerFactory;
 
 @SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
-@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-07-25")
+@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-07-26")
 public class FrontendRequest implements org.apache.thrift.TBase<FrontendRequest, FrontendRequest._Fields>, java.io.Serializable, Cloneable, Comparable<FrontendRequest> {
   private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FrontendRequest");
 
   private static final org.apache.thrift.protocol.TField TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("type", org.apache.thrift.protocol.TType.I32, (short)1);
   private static final org.apache.thrift.protocol.TField START_BUILD_FIELD_DESC = new org.apache.thrift.protocol.TField("startBuild", org.apache.thrift.protocol.TType.STRUCT, (short)2);
   private static final org.apache.thrift.protocol.TField BUILD_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("buildStatus", org.apache.thrift.protocol.TType.STRUCT, (short)3);
-  private static final org.apache.thrift.protocol.TField LOG_FIELD_DESC = new org.apache.thrift.protocol.TField("log", org.apache.thrift.protocol.TType.STRUCT, (short)4);
+  private static final org.apache.thrift.protocol.TField LOG_FIELD_DESC = new org.apache.thrift.protocol.TField("log", org.apache.thrift.protocol.TType.STRUCT, (short)6);
 
   private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
   static {
@@ -67,7 +67,7 @@
     TYPE((short)1, "type"),
     START_BUILD((short)2, "startBuild"),
     BUILD_STATUS((short)3, "buildStatus"),
-    LOG((short)4, "log");
+    LOG((short)6, "log");
 
     private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();
 
@@ -88,7 +88,7 @@
           return START_BUILD;
         case 3: // BUILD_STATUS
           return BUILD_STATUS;
-        case 4: // LOG
+        case 6: // LOG
           return LOG;
         default:
           return null;
@@ -624,7 +624,7 @@
               org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
             }
             break;
-          case 4: // LOG
+          case 6: // LOG
             if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
               struct.log = new LogRequest();
               struct.log.read(iprot);
