diff --git a/annotation/src/main/java/com/google/errorprone/BugPatternValidator.java b/annotation/src/main/java/com/google/errorprone/BugPatternValidator.java
index 9a08625..4a75a87 100644
--- a/annotation/src/main/java/com/google/errorprone/BugPatternValidator.java
+++ b/annotation/src/main/java/com/google/errorprone/BugPatternValidator.java
@@ -35,7 +35,7 @@
           throw new ValidationException("Expected a custom link but none was provided");
         }
         break;
-      case WIKI: case NONE:
+      case AUTOGENERATED: case NONE:
         if (!pattern.link().isEmpty()) {
           throw new ValidationException("Expected no custom link but found: " + pattern.link());
         }
